development:
  adapter: postgresql
  encoding: unicode
  database: herokuSample
  pool: 5
  username: postgres
  password: dathu_143
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: herokuSample
  pool: 5
  username: postgres
  password: dathu_143
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: herokuSample
  pool: 5
  username: postgres
  password: dathu_143